services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "FileUpload"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    container_name: backend
    volumes:
      - .:/app
      - /app/__pycache__
    env_file:
      - ./core/.env 
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_DEBUG=1
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres


  pgadmin:
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "alessail@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "Angel2041"
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
    attachable: true